[package]
name = "maker"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.1"
reqwest = "0.12.15"
tar = "0.4.44"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
