name: continuous deployment
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  extract-repo-info:
    runs-on: ubuntu-latest
    outputs:
      owner: ${{ steps.extract.outputs.owner }}
      repo: ${{ steps.extract.outputs.repo }}
    steps:
      - id: extract
        run: |
          echo "owner=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)" >> $GITHUB_OUTPUT
          echo "repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_OUTPUT

  build-publish:
    needs: extract-repo-info
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      actions: read
      contents: write
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: initialize Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
      - name: start Dagger
        run: . . | release-github env://GH_TOKEN ${{ needs.extract-repo-info.outputs.owner }} ${{ needs.extract-repo-info.outputs.repo }}
        shell: dagger {0}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
